config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show

  root to: 'pages#home'

  resources :users, only: [:index] do
    member do
      post :follow
      post :unfollow
    end
  end

  #user_chat
  resources :user_chats, only: :create  do
      resources :messages, only: %i[create destroy]
  end

  #faculdade
  resources :faculdades, only: %i[show index] do
    resources :reviews, only: :create
  end

  #curso
  resources :cursos, only: %i[show index]

  #opcao
  resources :opcaos, only: %i[show index]

  #user_opcao
  resources :user_opcaos, only: %i[create new destroy]
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_integrity_of  :photo
  validates_processing_of :photo
  validates :first_name, :last_name, presence: true

  has_many :user
  has_many :user_opcaos
  has_many :opcaos, through: :user_opcaos
  has_many :faculdades, through: :opcaos
  has_many :cursos, through: :opcaos

  has_many :user_chats, dependent: :destroy
  has_many :chats, through: :user_chats
  has_many :messages, through: :user_chats

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def is_following?(user_id)
    relationship = Follow.find_by(follower_id: id, following_id: user_id)
    return true if relationship
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name address phone_number age college])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name address phone_number age college])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:follow, :unfollow]
  skip_before_action :authenticate_user!, only: %i[show index]

  def index
    if current_user.present?
      @users = User.where.not(id: current_user.id)
    else
      @users = User.all
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def options
    render json: User.find(params[:id]).faculdades.pluck(:sigla)
  end

  def follow
    if current_user.follow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def unfollow
    if current_user.unfollow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render action: :follow }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_card.html.erb
<div class="op-card" data-index='<%= card_index %>' data-user-opcao='<%= user_opcao.id %>'>
  <div class="op-card-body">
    <% if @user == current_user %>
      <%= link_to "+", user_opcao_path(user_opcao), method: :delete, remote: true, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
    <% end %>
    <% if user_opcao.opcao.faculdade.photo.nil? %>
      <%= image_tag "https://images.unsplash.com/photo-1552515941-29d256554e11?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=890&q=80" %>
    <% else %>
      <img src='<%= user_opcao.opcao.faculdade.photo %>'>
    <% end %>
    <%= link_to opcao_path(user_opcao.opcao) do %>
      <div class="text-area">
        <h2 class="college"><%= user_opcao.opcao.curso.name %></h2>
        <h6><%= user_opcao.opcao.faculdade.name %></h6>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_card_grid.html.erb
<% user.user_opcaos.each do |user_opcao| %>
  <div class="op-card">
    <div class="op-card-body">
      <% if @user == current_user %>
        <%= link_to "+", user_opcao_path(user_opcao), method: :delete, remote: true, class: "card-remove-link" %>
      <% end %>
      <% if user_opcao.opcao.faculdade.photo.nil? %>
        <%= image_tag "https://images.unsplash.com/photo-1552515941-29d256554e11?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=890&q=80" %>
      <% else %>
        <img src='<%= user_opcao.opcao.faculdade.photo %>'>
      <% end %>
      <%= link_to opcao_path(user_opcao.opcao) do %>
        <div class="text-area">
          <h2 class="college"><%= user_opcao.opcao.curso.name %></h2>
          <h6><%= user_opcao.opcao.faculdade.name %></h6>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<li data-user=<%= user.id %>>
  <%= user.email %>
  <% if current_user.is_following?(user.id) %>
    <%= link_to "Unfollow", unfollow_user_path(user.id), method: :post, remote: true %>
  <% else %>
    <%= link_to "Follow", follow_user_path(user.id), method: :post, remote: true %>
  <% end %>
</li>

app/views/users/_user_card.html.erb
<% @user.following.each_with_index do |user, index| %>
   <div class="user-card">
    <div class="bg-img">
      <% if user.photo.present? %>
        <%= cl_image_tag user.photo, class: "avatar user-img", style: 'height:100px ;width:100px;object-fit:cover' %>
      <% else %>
        <%= image_tag "user.png", class: "avatar user-img", style: 'height:100px ;width:100px;object-fit:cover' %>
      <% end %>
    </div>
    <div class="user-text">
      <%= link_to user_path(user) do %>
      <p class="title"><%= "#{user.first_name} #{user.last_name}" %></p>
      <p class="email"><%=  user.email %></p>
      <% end %>
      <div class="button-container-card">
        <a href="#button" class="btn btn-round" rel="tooltip" title="Follow me on Twitter">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="#button" class="btn btn-round" rel="tooltip" title="Follow me on Instagram">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="#button" class="btn btn-round" rel="tooltip" title="Follow me on Facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </div>
    </div>
   </div>
<% end %>

app/views/users/follow.js.erb
function renderUser() {
  const user = document.querySelector("[data-user='<%= @user.id %>']");
  if (user.className === "card-add-link") {
    user.parentElement.insertAdjacentHTML("afterbegin", '<%= link_to "+", unfollow_user_path(@user.id), method: :post, remote: true, class: "card-remove-link", data: {user: "#{@user.id}"} %>');
    user.remove();
  }
  if (user.className === "card-remove-link") {
    user.parentElement.insertAdjacentHTML("afterbegin",'<%= link_to follow_user_path(@user.id), method: :post, remote: true, class: "card-add-link", data: {user: "#{@user.id}"} do %><i class="fas fa-heart"></i><% end %>');
    user.remove();
  }
}

if (window.location.pathname === "/users") {
  renderUser();
}

app/views/users/index.html.erb
<div class="container my-5 py-5">
  <div class="grids">
    <% @users.each do |user| %>
       <div class="user-card">
        <div class="bg-img">
          <% if user_signed_in? %>
            <% if current_user.is_following?(user.id) %>
              <%= link_to "+", unfollow_user_path(user.id), method: :post, remote: true, class: "card-remove-link", data: {user: "#{user.id}"} %>
            <% else %>
              <%= link_to follow_user_path(user.id), method: :post, remote: true, class: "card-add-link", data: {user: "#{user.id}"} do %>
                <i class="fas fa-heart"></i>
              <% end %>
            <% end %>
          <% end %>
          <% if user.photo.present? %>
            <%= cl_image_tag user.photo, class: "avatar user-img", style: 'height:100px ;width:100px;object-fit:cover' %>
          <% else %>
            <%= image_tag "user.png", class: "avatar user-img", style: 'height:100px ;width:100px;object-fit:cover' %>
          <% end %>
        </div>
        <div class="user-text">
          <%= link_to user_path(user) do %>
          <p class="title"><%= "#{user.first_name} #{user.last_name}" %></p>
          <p class="email"><%=  user.email %></p>
          <% end %>
          <div class="button-container-card">
            <a href="#button" class="btn btn-round" rel="tooltip" title="Follow me on Twitter">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="#button" class="btn btn-round" rel="tooltip" title="Follow me on Instagram">
              <i class="fab fa-instagram"></i>
            </a>
            <a href="#button" class="btn btn-round" rel="tooltip" title="Follow me on Facebook">
              <i class="fab fa-facebook"></i>
            </a>
          </div>
        </div>
       </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
  <div class="wrapper">
    <div class="page-header clear-filter page-header-small" filter-color="orange">
      <div class="page-header-image" data-parallax="true" style="background-image: linear-gradient(0deg,rgba(44,44,44,.2),rgba(224,23,3,.6)), url('https://images.unsplash.com/photo-1501503069356-3c6b82a17d89?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80');">
        <div class="profile-container">
          <% if @user.photo.present? %>
            <%= cl_image_tag @user.photo, class: "avatar user-img", style: 'height:150px ;width:150px;object-fit:cover' %>
          <% else %>
            <%= image_tag "user.png", class: "avatar user-img", style: 'height:150px ;width:150px;object-fit:cover' %>
          <% end %>
          <h3 class="title"><%= "#{@user.first_name} #{@user.last_name}" %></h3>
          <p class="category">Estudante</p>
          <div class="follow">
            <div class="followers">
              <h3 class="title">
                <%= @user.followers.count %>
              </h3>
              <p>Seguidores</p>
            </div>
            <div class="following">
              <h3 class="title">
                <%= @user.following.count %>
              </h3>
              <p>Seguindo</p>
            </div>
          </div>
          <div class="button-container">
            <a href="#button" class="btn btn-round" rel="tooltip" title="Follow me on Twitter">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="#button" class="btn btn-round" rel="tooltip" title="Follow me on Instagram">
              <i class="fab fa-instagram"></i>
            </a>
            <a href="#button" class="btn btn-round" rel="tooltip" title="Follow me on Facebook">
              <i class="fab fa-facebook"></i>
            </a>
            <a href="#button" class="btn btn-round" rel="tooltip" title="See calendar" data-toggle="modal" data-target="#exampleModal">
              <i class="fa fa-calendar" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="calendar-div">
            <div id="calendar">
            </div>
            <div class="modal-footer">
              <%= link_to "Close", user_path(@user), class: "btn btn-secondary" %>
            </div>
          </div>
        </div>
    <div class="section my-3">
      <div class="profile-container">
        <h3 class="title">Sobre mim</h3>
        <% if @user.infos %>
          <p class="description px-5"><%= @user.infos %></p>
        <% else %>
          <p class="description px-5"> Descrição? Só quero passar no vestibular!</p>
        <% end %>
        <h4 class="title text-center">Meus Cursos</h4>
        <div class="container">
        <% if @user.user_opcaos.size > 3 %>
          <div class="opcaos" id="opcaos">
            <% @user.user_opcaos.each_with_index do |user_opcao, index| %>
              <%= render 'card', user_opcao: user_opcao, card_index: index %>
            <% end %>
          </div>
        <% elsif @user.user_opcaos.size > 0 %>
          <div class="opcs" id="opcs">
            <%= render 'card_grid', user: @user %>
          </div>
        <% else %>
          <div class="no-choice">
            <h4>Você ainda não escolheu nenhum curso.</h4>
          </div>
        <% end %>
        </div>
    </div>
        <h4 class="title text-center mt-3" id="seguindo">Seguindo</h4>
        <div class="container">

        <% if @user.following.size > 3 %>
          <div class="follows" id="follows">
            <%= render 'user_card', user: @user %>
          </div>
        <% elsif @user.following.size > 0 %>
          <div class="opcs">
            <%= render 'user_card', user: @user %>
          </div>
        <% else %>
          <div class="no-choice">
            <h4>Você ainda não segue outro usuários.</h4>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>