config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show

  root to: 'pages#home'

  resources :users, only: [:index] do
    member do
      post :follow
      post :unfollow
    end
  end

  #user_chat
  resources :user_chats, only: :create  do
      resources :messages, only: %i[create destroy]
  end

  #faculdade
  resources :faculdades, only: %i[show index] do
    resources :reviews, only: :create
  end

  #curso
  resources :cursos, only: %i[show index]

  #opcao
  resources :opcaos, only: %i[show index]

  #user_opcao
  resources :user_opcaos, only: %i[create new destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-md-4 col-12 mb-2">
                <div class="footer-box-1">
                    <div class="footer_header">
                        <div class="footer_logo">
                            <%= image_tag "logo-white.png" %>
                        </div>
                    </div>
                    <div class="footer_box_body">
                      <div class="footer_social">
                        <a href="#"><i class="fab fa-facebook"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                      </div>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-4 mb-2">
              <div class="footer_header">
                  <h4 class="footer_title">
                      instagram
                  </h4>
              </div>
              <div class="footer_box_body">
                  <ul class="instagram_list">
                      <li>
                          <a href="#">
                              <img src="https://images.unsplash.com/photo-1503676382389-4809596d5290?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=755&q=80" alt="instagram">
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <img src="https://images.unsplash.com/photo-1523240795612-9a054b0db644?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="instagram">
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <img src="https://images.unsplash.com/photo-1460518451285-97b6aa326961?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="instagram">
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <img src="https://images.unsplash.com/photo-1529070538774-1843cb3265df?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="instagram">
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <img src="https://images.unsplash.com/photo-1519664993241-d7c8f0ae7b39?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="instagram">
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <img src="https://images.unsplash.com/photo-1416677357736-79cd2bce22c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=780&q=80" alt="instagram">
                          </a>
                      </li>
                  </ul>
              </div>
            </div>

            <div class="col-12 col-md-4">
                <div class="footer-box-2">
                  <div class="footer_header">
                      <h4 class="footer_title">
                          receba nossa newsletter
                      </h4>
                  </div>
                  <div class="footer-box-body">
                      <div class="newsletter_form">
                          <input type="email" class="form-control" placeholder="E-Mail here">
                          <button class="button">Inscreva-se</button>
                      </div>
                      <div class="footer_menu">
                        <%= link_to "Home", root_path %>
                        <a href="#">Contato</a>
                        <a href="#">Política de Privacidade</a>
                      </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-md navbar-lewagon transparent fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo-white.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"><i class="fas fa-bars"></i> </span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Cursos", opcaos_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Faculdades", faculdades_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Carreiras", cursos_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Usuários", users_path, class: "nav-link" %>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown dropdown-left">
          <% if current_user.photo.present? %>
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", style: 'height:50px ;width:50px;', id: "navbarDropdown",   data: { toggle: "dropdown"}, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
          <%= image_tag 'user.png', class: "avatar dropdown-toggle", style: 'height:50px ;width:50px;object-fit:cover', id: "navbarDropdown",   data: { toggle: "dropdown"}, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Perfil", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Seus dados", edit_user_registration_path, class: "dropdown-item" %>

            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
      <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>