config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show

  root to: 'pages#home'

  resources :users, only: [:index] do
    member do
      post :follow
      post :unfollow
    end
  end

  #user_chat
  resources :user_chats, only: :create  do
      resources :messages, only: %i[create destroy]
  end

  #faculdade
  resources :faculdades, only: %i[show index] do
    resources :reviews, only: :create
  end

  #curso
  resources :cursos, only: %i[show index]

  #opcao
  resources :opcaos, only: %i[show index]

  #user_opcao
  resources :user_opcaos, only: %i[create new destroy]
end

app/models/curso.rb
class Curso < ApplicationRecord
  has_many :opcaos
  has_many :faculdades, through: :opcaos
  has_one :chat
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show index]
  def index
    if params[:curso].present?
      @cursos = Curso.where("name ILIKE ?", "%#{params[:curso]}%").page(params[:page]).per(16)
    else
      @cursos = Curso.all.page(params[:page]).per(16)
    end
  end

  def show
    @curso = Curso.find(params[:id])
    @redirect = @curso.id
  end
end

app/views/cursos/index.html.erb
<div class="search">
  <%= form_tag cursos_path, method: :get do %>

    <%= text_field_tag :curso,
    params[:curso],
    class: "form-control query" ,
    placeholder: "Busca uma categoria"%>

    <%= button_tag type: 'submit', class: "button-opc" do %>
      <span class="my-0"> Buscar </span></i>
    <% end %>
    <%= link_to "Ver todas", cursos_path, class: "button-ocp" %>
  <% end %>
</div>

<div class="container py-5">
  <div class="grids">
    <% @cursos.shuffle.each do |curso| %>
      <div class="fac-card" data-aos="zoom-in">
        <% if curso.photo.nil? %>
        <%= image_tag "Artes-humanas.jpg", height: 175, width: 265%>
        <% else %>
        <%= image_tag curso.photo, height: 175, width: 265 %>
        <% end %>
        <%= link_to curso_path(curso), class: "curso" do %>
        <div class="text-area">
          <h2 class="college"><%= curso.ocde_geral %></h2>
          <h6><%= curso.name  %></h6>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= paginate @cursos, class: "paginate" %>
</div>

app/views/cursos/show.html.erb
<% image = image_path('facul.jpg') %>
<section class="hero image-as-background" style="background-image: url('<%= image %>');">

  <div class="hero-container">
    <h1 class="hero-title animate fadeInLeft delay-600"><%= @curso.name.capitalize %></h1>
  </div>

</section>


<section class="main-content">

  <div class="text">
  <h2>Saiba mais sobre esse curso</h2>
  <p>Busque por mais informações sobre esse curso em nosso fórum sobre <%= @curso.name.capitalize %>. Discuta com outras pessoas suas dúvidas, medos, felicidades e descubra mais sobre a carreira de sua escolha.</p>
  <p>Não esqueça de procurar pelas melhores faculdades no ranking ao lado e não perder nenhuma informação enquanto se prepara para o tão esperado vestibular</p>
  <p>O ranking ao lado utiliza como base o Ranking da Folha(RUF) para classificar as faculdades do Brasil. As notas são definidas com base em dados nacionais e internacionais e em duas pesquisas de opinião do Datafolha em cinco aspectos (pesquisa, ensino, mercado, internacionalização e inovação)</p>
  </div>

  <div class="container-index">

    <div class="table">

      <div class="table-header">
        <div class="header__item"><p>Faculdades</p></div>
        <div class="header__item"><p>Posição</p></div>
        <div class="header__item"><p>Notas</p></div>
        <div class="header__item"><p>Situação</p></div>
      </div>

      <% @curso.faculdades.order(:ranking).first(5).each do |f| %>

      <div class="table-content">

        <div class="table-row">

          <div class="table-data"><%= link_to f.sigla == "-" ? f.name : f.sigla, opcao_path(Opcao.where(curso_id: @curso, faculdade_id: f).first) %></div>
          <div class="table-data"><%= f.ranking %>º</div>
          <div class="table-data"><%= f.nota %></div>
          <div class="table-data">Ativa</div>
        </div>

      <% end %>
      </div>

        <%= form_tag opcaos_path, method: :get do %>
          <%= text_field_tag :opçao,
          @redirect,
          class: "form-control query d-none"%>

          <%= button_tag type: 'submit', class: "btn orange-btn w-100" do %>
            <span class="my-0"> Ver mais </span></i>
          <% end %>
        <% end %>
    </div>
  </div>
</section>

<% if user_signed_in? %>
  <div class="modal fade" id="chatModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
    </div>
      <%= render 'messages/chat' %>
  </div>
  <div id="btn-place">
  <% if current_user.user_chats.where(chat: @curso.chat).present? %>
    <button type="button" class="chat-open" data-toggle="modal" data-target="#chatModal">
      <i class="far fa-comments"></i>
    </button>
  <% else %>
    <%= link_to user_chats_path(chat: @curso.chat), method: :post, remote: :true, class: "chat-open" do %>
      <i class="far fa-comments"></i>
    <% end %>
  <% end %>
  </div>
<% else %>
  <%= link_to user_session_path, class: "chat-open" do %>
    <i class="far fa-comments"></i>
  <% end %>
<% end %>