config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show

  root to: 'pages#home'

  resources :users, only: [:index] do
    member do
      post :follow
      post :unfollow
    end
  end

  #user_chat
  resources :user_chats, only: :create  do
      resources :messages, only: %i[create destroy]
  end

  #faculdade
  resources :faculdades, only: %i[show index] do
    resources :reviews, only: :create
  end

  #curso
  resources :cursos, only: %i[show index]

  #opcao
  resources :opcaos, only: %i[show index]

  #user_opcao
  resources :user_opcaos, only: %i[create new destroy]
end

app/models/opcao.rb
class Opcao < ApplicationRecord
  belongs_to :faculdade
  belongs_to :curso
end

app/controllers/opcaos_controller.rb
class OpcaosController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show index]
  before_action :set_facu, only: :index

  def show
    @opcao = Opcao.find(params[:id])
  end

  def index
    @opcaos = Opcao.all.order(:photo).page(params[:page]).per(16)

    if params[:facu].present? && params[:opçao].present?
      @opcaos = Opcao.joins(:faculdade).where("sigla ILIKE ? AND ocde_curso ILIKE ?", "%#{params[:facu]}%",
                                              "%#{params[:opçao]}%").page(params[:page]).per(16)
    elsif params[:opçao].present?

      if params[:opçao].to_i != 0
        @opcaos = Opcao.where("curso_id = ?", "#{params[:opçao]}").page(params[:page]).per(16)
      else
        @opcaos = Opcao.where("ocde_curso ILIKE ?", "%#{params[:opçao]}%").page(params[:page]).per(16)
      end

    elsif params[:facu].present?
      @opcaos = Opcao.joins(:faculdade).where("sigla ILIKE ?", "%#{params[:facu]}%").page(params[:page]).per(16)

    else
      @opcaos

    end
  end

  private

  def set_facu
    @faculdade = Faculdade.where(name: params[:query_facu])
  end
end

app/views/opcaos/_following_opcao.js.erb
// const buttonFollow = document.querySelector('.opcao_following');
// const buttonUnfollow =  document.querySelector('.opcao_unfollowing');

// const unfollowOpcao = () => {
//   buttonFollow.addEventListener('click',()=> {
//     console.log("unfollow")
//     buttonFollow.innerHTML = '<%= link_to "Parar de seguir", user_opcao_path(current_user.user_opcaos.where(opcao: @opcao).pluck(:id)), method: :delete, remote: true,class: "btn btn-danger opcao_unfollowing", data: {id: "#{@opcao.id}"} %>'
//   })
// }

// const followOpcao = () => {
//   buttonUnfollow.addEventListener('click', () => {
//     console.log("Follow")
//     buttonUnfollow.innerHTML = '<%= link_to "Seguir",user_opcaos_path(@opcao), method: :post, remote: true,class: "btn btn-secondary opcao_following", data: {id: "#{@opcao.id}"} %>'
//   })
// }

// if (buttonUnfollow) {
//   followOpcao();
// }

// if (buttonFollow) {
//   unfollowOpcao();
// }
// const clickFollow = () => {
//   const buttonFollow = document.querySelector('.opcao_following');
//   const buttonUnfollow = document.querySelector('.opcao_unfollowing');
//   if (buttonFollow) {
//     buttonFollow.addEventListener('click', () => {
//       console.log("Follow")
//       buttonFollow.innerText = 'Parar de seguir'
//       buttonFollow.style.backgroundColor = '$orange-bg'
//     })
//   } else if (buttonUnfollow) {
//     buttonUnfollow.addEventListener('click', () => {
//       console.log("Unfollow")
//       buttonUnfollow.innerText = 'Seguir'
//       buttonUnfollow.style.backgroundColor = 'orange'
//     })
//   }
// }

// export default clickFollow;

app/views/opcaos/index.html.erb
<div class="search">
  <%= form_tag opcaos_path, method: :get do %>

    <%= text_field_tag :opçao,
      params[:opçao],
      class: "form-control query",
      placeholder: "Busca uma matéria"%>

    <%= text_field_tag :facu,
    params[:facu],
    class: "form-control query" ,
    placeholder: "Busca uma faculdade"%>

    <%= button_tag type: 'submit', class: "button-opc" do %>
      <span class="my-0"> Buscar </span></i>
    <% end %>
    <%= link_to "Ver todas", opcaos_path, class: "button-ocp" %>
  <% end %>
</div>


<div class="container py-5">
  <div class="grids">
    <% @opcaos.shuffle.each do |opcao| %>
      <div class="fac-card" data-aos="zoom-in">
        <% if user_signed_in? %>
           <%= link_to user_opcaos_path(opcao: opcao), method: :post, remote: true, class: "card-add-link", alt: "seguir curso" do %>
            <i class="fas fa-heart"></i>
           <% end %>
        <% end %>
        <% if opcao.faculdade.photo.nil? %>
        <%= image_tag "Educacao.jpg", height: 175, width: 265 %>
        <% else %>
        <img src="<%= opcao.faculdade.photo %>" style="height: 175, width: 265"alt="">
        <% end %>
        <%= link_to opcao_path(opcao), class: "faculdade" do %>
        <div class="text-area">
          <h2 class="college"><%= opcao.curso.name  %></h2>
          <h6><%= opcao.faculdade.name %></h6>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= paginate @opcaos, class: "paginate" %>
</div>

app/views/opcaos/show.html.erb
<% image = image_path('graduation.png') %>
<div class="app" style="background-image: url('<%= image %>');">
  <main>

    <h1><%= @opcao.curso.name %> EM <%= @opcao.faculdade.name %></h1>
    <% if user_signed_in? %>
        <% if current_user.user_opcaos.where(opcao: @opcao).present? %>
        <h2>
          <%= link_to "Parar de seguir",
          user_opcao_path(current_user.user_opcaos.where(opcao: @opcao).pluck(:id)),
          method: :delete,
          remote: true,
          class: "btn btn-danger opcao_unfollowing",
            data: {id: "#{@opcao.id}"} %>
        </h2>
      <% else %>
        <h2>
          <%= link_to "Seguir",
          user_opcaos_path(opcao: @opcao),
          method: :post,
          remote: true,
          class: 'btn btn-secondary opcao_following',
          data: {id: "#{@opcao.id}"} %>
        </h2>
      <% end %>
    <% end %>
  </main>
</div>
<% notas = image_path('notas.jpg') %>
<ul class="cards">
  <li class="cards__item">
    <div class="cardin">
      <div class="cardin__image" style="background-image: url('<%= notas %>');"></div>
      <div class="cardin__content">
        <div class="cardin__title">As notas:</div>
        <p class="cardin__text">Ranking da Folha(RUF): <%= @opcao.faculdade.ranking %>º</p>
        <% if @opcao.enade == 0 && @opcao.cc == 0 %>
          <p class="cardin__text">Conceito de Curso (CC): SEM NOTA</p>
        <% elsif @opcao.enade == 0 %>
          <p class="cardin__text">Conceito de Curso (CC):
          <% @opcao.cc.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% (5 - @opcao.cc).times do %>
            <i class="far fa-star"></i>
          <% end %>
          </p>
        <% else %>
          <p class="cardin__text">ENADE(MEC):
          <% @opcao.enade.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% (5 - @opcao.enade).times do %>
            <i class="far fa-star"></i>
          <% end %>
          </p>
        <% end %>
      </div>
    </div>
  </li>
  <% datas = image_path('datas.png') %>
  <li class="cards__item">
    <div class="cardin">
      <div class="cardin__image" style="background-image: url('<%= datas %>');"></div>
      <div class="cardin__content">
        <div class="cardin__title">Datas Importantes:</div>
        <% if @opcao.data_inscricao.present? %>
        <p class="cardin__text">Data de inscrição: <%= @opcao.data_inscricao %>
        <% else %>
        <p class="cardin__text">Data de inscrição: 22/10/2019
        </p>
        <% end %>
        <% if @opcao.data_prova.present? %>
        <p class="cardin__text">Data de prova: <%= @opcao.data_prova %>
        <% else %>
        <p class="cardin__text">Data de prova: 22/11/2019
        </p>
        <% end %>
      </div>
    </div>
  </li>
  <% infos = image_path('infos.png') %>
  <li class="cards__item">
    <div class="cardin">
      <div class="cardin__image" style="background-image: url('<%= infos %>');"></div>
      <div class="cardin__content">
        <div class="cardin__title">Outras Informações:</div>
        <p class="cardin__text">Número de vagas: <%= @opcao.vagas %></p>
        <p class="cardin__text">Tipo do curso: <%= @opcao.grau %></p>
      </div>
    </div>
  </li>
</ul>


<%#= javascript_tag do %>
  <%#= render(:partial => 'following_opcao', :handlers => [:erb], :formats => [:js]) %>
<%# end %>